encrypt:
  key: ${ENCRYPT_KEY}
spring:
  application:
    name: bugtracker1
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      label: main
      username: ${CLOUD_CONFIG_USER}
      password: ${CLOUD_CONFIG_PASS}
management:
  endpoints:
    web:
      exposure:
        include: refresh