spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/pluralsight/protocol/openid-connect/certs